### ISSUE TITLE
Request Openshift Namespace

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/forest-client-api#10]

**Comment by ConradBoydElliottGustafson** [comment]
@DerekRoberts In progress?

**Comment by DerekRoberts** [comment]
@ConradBoydElliottGustafson in progress!  So far, so confused, but already on it.

https://developer.gov.bc.ca/topic/featured/Service-Overview-for-BC-Government-Private-Cloud-as-a-ServiceOpenshift-4-Platform

**Comment by ConradBoydElliottGustafson** [comment]
@DerekRoberts I haven't requested a namespace before, but if you get blocked and think I can help, just let me know.

**Comment by DerekRoberts** [comment]
![Screenshot from 2022-01-27 11-09-32](https://user-images.githubusercontent.com/4391600/151427375-cabe24e0-e7cc-4c55-aee0-29fdd8ea74a5.png)

**Comment by DerekRoberts** [comment]
Namespace Details
--
OpenShift Cluster:Silver Hosting TierDev Namespace:d2723f-devTest Namespace:d2723f-testProd Namespace:d2723f-prodTools Namespace:d2723f-tools | OpenShift Cluster: | Silver Hosting Tier | Dev Namespace: | d2723f-dev | Test Namespace: | d2723f-test | Prod Namespace: | d2723f-prod | Tools Namespace: | d2723f-tools
OpenShift Cluster: | Silver Hosting Tier
Dev Namespace: | d2723f-dev
Test Namespace: | d2723f-test
Prod Namespace: | d2723f-prod
Tools Namespace: | d2723f-tools
