### ISSUE TITLE
Create OpenAPI spec for forest client API

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/forest-client-api#13]

**Comment by ConradBoydElliottGustafson** [comment]
Created an API spec for review here: https://raw.githubusercontent.com/bcgov/forest-client-api/swagger-definition/src/api/swagger.yaml

Also generated some golang server code just to see how it would turn out.

**Comment by DerekRoberts** [comment]
@ConradBoydElliottGustafson Looks good!  Should we queue up building this?

**Comment by ConradBoydElliottGustafson** [comment]
I think it's a start. Love to get Kevin's feedback as well! @franTarkenton

**Comment by franTarkenton** [comment]
Looks great @ConradBoydElliottGustafson Looking forward to building it.  Would love to get a walk though of the tooling that you used to create it.

**Comment by ConradBoydElliottGustafson** [comment]
I updated the branch with the change @webgismd suggested. I removed the "cache-time" parameter and response value from the "get all" request. Simple and easy! Optimize later! I love this approach. Now we can ask for a proxy account that can read from the view instead of going to the table (the view doesn't have the update time field).
